version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build:
      context: ./  # โฟลเดอร์ที่มี Dockerfile
      dockerfile: Dockerfile  # ระบุชื่อไฟล์ Dockerfile (default คือ Dockerfile)
    container_name: kuty-backend
    image: kuty-backend:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
